
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "3002:3002"
    depends_on:
      - oleg-proj-postgres
      - oleg-proj-redis
    restart: on-failure


  oleg-proj-postgres:
    image: postgres:16.1
    ports:
      - '${POSTGRES_PORT:-5436}:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-user}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'
      POSTGRES_DB: '${POSTGRES_DB:-oleg-proj}'
    volumes:
      - oleg-proj-api-db:/var/lib/postgresql/data

  oleg-proj-redis:
    image: redis:7.2.3
    ports:
      - '${REDIS_PORT:-6379}:6379'
    env_file:
      - .env
    command: redis-server
    restart: unless-stopped

  oleg-proj-s3:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9002"
    restart: unless-stopped
    ports:
      - "8000:9000"
      - "8002:9002"
    volumes:
      - ./backend/oleg-proj-api-s3-data:/usr/src/app/s3
    environment:
      - MINIO_ROOT_USER=user            # AWS_S3_ACCESS_KEY
      - MINIO_ROOT_PASSWORD=password    # AWS_S3_SECRET_KEY

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure

volumes:
  oleg-proj-api-db:
  oleg-proj-api-s3:

