export enum CarBrandEnum {
  HORSE = 'horse',
  BMW = 'BMW',
  PORSCHE = 'Porsche',
  MERCEDES_BENZ = 'Mercedes-Benz',
  AUDI = 'Audi',
  TOYOTA = 'Toyota',
  HONDA = 'Honda',
  FORD = 'Ford',
  CHEVROLET = 'Chevrolet',
  TESLA = 'Tesla',
  NISSAN = 'Nissan',
  VOLKSWAGEN = 'Volkswagen',
  VOLVO = 'Volvo',
  LEXUS = 'Lexus',
  SUBARU = 'Subaru',
  MAZDA = 'Mazda',
  JAGUAR = 'Jaguar',
  FERRARI = 'Ferrari',
  LAMBORGHINI = 'Lamborghini',
  MASERATI = 'Maserati',
  ROLLS_ROYCE = 'Rolls-Royce',
}
